### ISSUE TITLE
Changing exception type for from_device_file broke backward compatibility

### ISSUE THREAD

**Issue by dtantsur** [pyudev/pyudev#129]
The commit https://github.com/pyudev/pyudev/commit/013af2ce0fd3378f69274b3852bd4e48ba3c1a44 changes the exception for from_device_file. Everyone who expected to catch (EnvironmentError, ValueError) might get broken now, see e.g. https://bugs.launchpad.net/ironic-python-agent/+bug/1522756.

Is it possible to inherit DeviceNotFoundByFileError from python EnvironmentError?

**Comment by mulkieran** [comment]
Please consider catching DeviceNotFoundError in addition to the other exceptions.

Feel free to reopen if that is not a workable solution.

**Comment by dtantsur** [comment]
It's possible, even though not very convenient. This, however, raises even more important question: what policies does pyudev have in place re backward compatibilities? should we expect every release to be potentially breaking and thus pin pyudev to a particular version for OpenStack consumers (including RHOS)?

**Comment by mulkieran** [comment]
Please check your personal email for a more complete answer.

**Comment by jayofdoom** [comment]
I'd really appreciate it if you'd post it here, in public. I am also someone who works on the OpenStack project this depends on and have a vested interest in making sure things stay unbroken.

Thanks!

**Comment by mulkieran** [comment]
@jayofdoom  You are welcome, nay encouraged, to open a new issue regarding the broader issue of backwards compatibility, versioning, etc. Even in this day and age when it is so common, I'm still reluctant to share anything that was told in private to me without getting the explicit consent of the other people involved. That being said, I hereby give @dtantsur explicit permission to share whatever I said in the conversation w/ you and any other open stack contributors or people in general he wants to share it with.

**Comment by dtantsur** [comment]
@jayofdoom sorry, did not mean to exclude you. I've communicated our problem, we discussed the solution, which resulted in https://review.openstack.org/#/c/253454/, then I suggested switching to semver and defining a stable API and offered my help with these 2, if needed. I was told that API is not stable yet, so we should probably keep an eye on what's going on with pyudev until it reaches 1.0.

**Comment by dtantsur** [comment]
@jayofdoom @mulkieran I've filed https://github.com/pyudev/pyudev/issues/131 to track API and versioning.
