### ISSUE TITLE
shouldn't MonitorObserver pass the action to the registered callback?

### ISSUE THREAD

**Issue by dwlehman** [pyudev/pyudev#137]
If `MonitorObserver` passed the action along with the device to the callback it would be a suitable replacement for `event_handler`. As it stands now, if you pass callback= to the ctor you only get the device passed when an event is received.

**Comment by mulkieran** [comment]
The device has an action property that gets extracted and passed.

This seems to be the relevant libudev method:
https://www.kernel.org/pub/linux/utils/kernel/hotplug/libudev/libudev-udev-device.html#udev-device-get-action

**Comment by mulkieran** [comment]
Please reopen if this is not an adequate answer.
