### ISSUE TITLE
ORing different properties isn't ideal

### ISSUE THREAD

**Issue by rbalik** [pyudev/pyudev#227]
If I do `context.list_devices(ID_VENDOR_ID=vid, ID_MODEL_ID=pid)` it would make sense that I'm trying to get a device with a the VID I specify AND the PID that I specify, but pyudev actually does an OR.

I can understand that if I did `ID_VENDOR_ID=vid1, ID_VENDOR_ID=vid2` then maybe I want to OR them and get both, but if they're different like above then it seems like an AND makes more sense.

**Comment by mulkieran** [comment]
```list_devices()``` is a very thin wrapper around calls to the underlying libudev library and it's passing on the semantics of that library quite directly. I'm not sure why libudev chose that particular semantics, but that is unlikely to change.

See #1 for some further discussion.

**Comment by rbalik** [comment]
Ah ok, thanks. I guess I'll close this. It's not really hard to workaround in the case I listed above but just too bad can't do it all with one line of code.
