### ISSUE TITLE
import pyudev fails due to errono.EOVERFLOW not being defined

### ISSUE THREAD

**Issue by MickeyM79** [pyudev/pyudev#228]
I'm using Python(x,y) which is version 2.7.10 and pyudev-0.21 on a Windows 7 64bit machine.
pyudev was installed via pip install pyudev

Starting the python interactive console and importing pyudev results in the following error.

Python 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)] on win32
<snip>
  File "C:\Python27\lib\site-packages\pyudev\_ctypeslib\_errorcheckers.py", line 38, in <module>
    errno.EOVERFLOW: OverflowError,
AttributeError: 'module' object has no attribute 'EOVERFLOW'

I imported errno and dumped it, and there is no EOVERFLOW. See attached file for dump.

I'm not sure if this is an error with the errno Module just not being complete, or if it's something pyudev should be able to handle, since there apparently is a python package with EOVERFLOW not defined.

Attached is the full error and errno dump.
[pyudev error.txt](https://github.com/pyudev/pyudev/files/1679048/pyudev.error.txt)

**Comment by mulkieran** [comment]
I'm afraid pyudev is and always has been Linux only.

**Comment by mulkieran** [comment]
This comes up every so often: #185.

**Comment by MickeyM79** [comment]
That makes sense then.  Is the functionality available in windows?  If so I may take a stab at making it work..

**Comment by mulkieran** [comment]
I think there might be no purpose, since udev is, itself, Linux specific.

**Comment by MickeyM79** [comment]
Okay. Thank you.
