### ISSUE TITLE
Queue interface

### ISSUE THREAD

**Issue by lunaryorn** [pyudev/pyudev#28]
Provide interface to the udev event queue as exposed by the `udev_queue_*` functions from libudev.

**Comment by mulkieran** [comment]
I'm closing this because of what current libudev docs say:

Furthermore, libudev also exports legacy APIs that should not be used
       by new software (and as such are not documented as part of this
       manual). This includes the hardware-database known as udev_hwdb (please
       use the new sd-hwdb(3) API instead) and the udev_queue object to query
       the udev-daemon (which should not be used by new software at all).
