### ISSUE TITLE
`ID_INPUT_*` udev properties of a Device object

### ISSUE THREAD

**Issue by Atalanttore** [pyudev/pyudev#361]
I would like to get the `ID_INPUT_*` [udev properties](https://wayland.freedesktop.org/libinput/doc/latest/device-configuration-via-udev.html?highlight=id_input) of a Device object, but it doesn't seem to be supported.

```
import pyudev


class USBMonitor:

    def __init__(self):
        self._context = pyudev.Context()
        self._monitor = pyudev.Monitor.from_netlink(self._context)
        self._monitor.filter_by('usb')
        self._monitor.start()

        for device in iter(self._monitor.poll, None):
            print(device.get('DEVTYPE'))
            print(device.get('ID_INPUT_KEYBOARD')) # returns always 'None'
            # How to get ID_INPUT_* properties of device here?


if __name__ == "__main__":
    usb_monitor = USBMonitor()
```

**Comment by mulkieran** [comment]
@Atalanttore pyudev uses libudev to get all properties that are available. The most likely explanation is that ```ID_INPUT_KEYBOARD``` is not being supplied by udev for some or more devices that you are polling. Possibly, you can use the command-line tool udevadm to verify this.

**Comment by Atalanttore** [comment]
Is there another way to filter by `ID_INPUT_KEYBOARD` as the `list_devices()` method of a `Context()` object does?

```
from pyudev import Context
context = Context()
for device in context.list_devices(subsystem='input', ID_INPUT_KEYBOARD=True):
    if device.sys_name.startswith('event'):
        print(device.parent['NAME'])
```

**Comment by mulkieran** [comment]
There's no built in libudev way to do that, unfortunately.

**Comment by mulkieran** [comment]
If more question, please reopen.
