### ISSUE TITLE
Can't restart a MonitorObserver

### ISSUE THREAD

**Issue by galak** [pyudev/pyudev#363]
After we stop an observer it would be nice to be able restart it.

Here's a simple test that shows the issue:
```
import pyudev

def udev_event_callback(dev):
    print('background event {0.action}: {0.device_path}'.format(dev))

context = pyudev.Context()
monitor = pyudev.Monitor.from_netlink(context)
observer = pyudev.MonitorObserver(monitor, callback=udev_event_callback, name='monitor-observer')
observer.start()
observer.stop()
observer.start()
```

Output we get:
```
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    observer.start()
  File "/usr/lib/python3.7/site-packages/pyudev/monitor.py", line 515, in start
    Thread.start(self)
  File "/usr/lib64/python3.7/threading.py", line 843, in start
    raise RuntimeError("threads can only be started once")
RuntimeError: threads can only be started once
```

**Comment by mulkieran** [comment]
I think you'll have to just remake the MonitorObserver, if you want it to run again. The design of the MonitorObserver is that it, itself, inherits from Thread, so it must obey the Thread rules that the Python standard library enforces. To be able to restart an observer would require a redesign such that it does not inherit from Thread, i.e., it would be a significant project and change.

**Comment by galak** [comment]
ok, makes sense to me.  wasn't sure if python threads let you call start again.
