### ISSUE TITLE
How to handle non unicode characters in device properties?

### ISSUE THREAD

**Issue by DustinKingen** [pyudev/pyudev#370]
I have a Samsung 970 Pro SSD and the output of `udevadm info -p` shows a non-unicode character `0xe1` on the property PARTNAME=á!!:

    udevadm info -p /devices/pci0000:00/0000:00:1b.0/0000:02:00.0/nvme/nvme0/nvme0n1/nvme0n1p1 | grep -a 'PARTNAME' | cut -c13- | od -vAn -tcx1
     341   !   !  \n
      e1  21  21  0a

This results in an exception whenever [`ensure_unicode_string`](https://github.com/pyudev/pyudev/blob/fa2789694c84c7120ecc7bf9e4647914482e8665/src/pyudev/_util.py#L55) is called in a member of the [`Properties`](https://github.com/pyudev/pyudev/blob/fa2789694c84c7120ecc7bf9e4647914482e8665/src/pyudev/device/_device.py#L1014) class, for example [`__iter__`](https://github.com/pyudev/pyudev/blob/fa2789694c84c7120ecc7bf9e4647914482e8665/src/pyudev/device/_device.py#L1035).

Example code from [blivet](https://github.com/storaged-project/blivet/blob/fa9ee18bbd305845ff970b2a322fb60ef399ecf6/blivet/udev.py#L53):
[Related issue](https://bugzilla.redhat.com/show_bug.cgi?id=1573555)

```python3
def device_to_dict(device):
    # Transform Device to dictionary
    # Originally it was possible to use directly Device where needed,
    # but it lead to unfixable excessive deprecation warnings from udev.
    # Sice blivet uses Device.properties only (with couple of exceptions)
    # this is a functional workaround. (japokorn May 2017)

    # **Exception thrown here on my machine**
    result = dict(device.properties)
    result["SYS_NAME"] = device.sys_name
    result["SYS_PATH"] = device.sys_path
    return result
```
Do you know if there is a workaround available?

**Comment by mulkieran** [comment]
If you are trying to get the PARTNAME via some method or perhaps index operator on the Properties class, I'm afraid you will find an exception is raised in the context in which you seem to be operating. This is a long-standing problem, and so far no solution has been arrived at. Some PRs have been put up, but they have had a "break it for everybody else" sort of quality, and so I haven't been able to accept them. It's a difficult problem, and needs to be addressed carefully.

**Comment by DustinKingen** [comment]
Thanks for the response @mulkieran!

Sorry I didn't notice the outstanding PR: https://github.com/pyudev/pyudev/pull/230

I'll research more into this issue. It seems to me there is a more underlying of why `PARTNAME` is getting set to a non-unicode format. My hypothesis is this has something to do with Windows/NTFS and how udev is exposing this information from systemd.

I'll close this for now.

**Comment by mulkieran** [comment]
Ok! And good luck w/ whatever your working on.

**Comment by DustinKingen** [comment]
FYI I found a workaround for my use case of installing Fedora.

1) Open Disks 
2) Edit the partitions (Boot and Windows in my case)
3) Delete the bad characters
4) Save

Windows will continue to work as normal.
