### ISSUE TITLE
AttributeError: module 'pytest' has no attribute 'config'

### ISSUE THREAD

**Issue by mulkieran** [pyudev/pyudev#378]
Need to figure out an alternative to the ```check_privileges_or_skip``` method implementation, since config attribute is gone in newer versions of pytest.

```
    def check_privileges_or_skip():
>       if not pytest.config.option.enable_privileged:
E       AttributeError: module 'pytest' has no attribute 'config'
```

**Comment by mulkieran** [comment]
@FFY00 Have you any ideas about how to fix this? It happens reliably on my system on

```
> tox -e test
```

**Comment by FFY00** [comment]
Hey, sorry for the late response.

```python
@pytest.fixture
    def enable_privileged(request):
        return request.config.getoption('--enable-privileged')

def check_privileges_or_skip(enable_privileged):
    if not enable_privileged:
        pytest.skip('privileged tests disabled')
```

**Comment by mulkieran** [comment]
Thanks! I could never get it to work, and it is almost never used, so I'm just removing this test functionality.

See #389 .
