### ISSUE TITLE
How to robustly monitor device addition and removal?

### ISSUE THREAD

**Issue by ali1234** [pyudev/pyudev#417]
Example code:

```
def serial_add(action, device):
    if device.get('ID_MODEL', None) == '32Blit_CDC':
        print(action, device['DEVNAME'])

context = pyudev.Context()
monitor = pyudev.Monitor.from_netlink(context)
monitor.filter_by('tty')
observer = pyudev.MonitorObserver(monitor, serial_add)
observer.start()

while True:
    pass
```
This code will print a message whenever a device is added or removed from the system. How do I handle devices that are already connected when the program runs?

I can query for existing devices as follows:
```
for device in context.list_devices(subsystem='tty'):
    serial_add(None, device)
```

However, if I run this code before starting the monitor, then it is possible to miss devices which are connected after it runs but before the monitor starts. On the other hand, If I run this code after starting the monitor, then it is possible to receive duplicate notifications if a device as added after the monitor starts but before existing devices are scanned.

How do I handle this correctly so that I never miss devices or get duplicate notifications?

**Comment by mulkieran** [comment]
This is the eternal problem, I'm afraid. Most people solve it by both listing and monitoring and sorting out the results somehow, by figuring out when devices are identical. It is always a pain.

**Comment by ali1234** [comment]
Thanks. I suspected that might be the case.
