### ISSUE TITLE
Messy tagging

### ISSUE THREAD

**Issue by kloczek** [pyudev/pyudev#422]
Pypi shows that last version os 0.22.0 however git tag is `v0.22`.
I have some automation which relies on git tags.
May I ask to match in the puture git version tags with actual version string?

**Comment by mulkieran** [comment]
I imagine it is a mistake that version 0.22.0 got tagged as 0.22. Since 0.18, patch version has always been included in the tag, and I expect it will be included in the future.

**Comment by kloczek** [comment]
Issue is that I'm trying to package you module as rpm and IPS packages and I found that sdist tar ball has no included documentation. To build/publish those packaged I cannot use autogenerated from tag tar ball because there is no 0.22.0. and this is the latest version according to https://pypi.org/project/pyudev/.

Really . may ask correct or add tag for 0.22.0?
Please ..
