### ISSUE TITLE
No read permissions for .egg-info files in PyPI tarball

### ISSUE THREAD

**Issue by Staudey** [pyudev/pyudev#441]
While packaging some things for Solus I ran into a permission error with pyudev versions >= 0.23

After a quick look I noticed that starting with that version the package built **from the PyPI tarball** results in following files having no read permissions for other users:
![image](https://user-images.githubusercontent.com/6317346/151687830-7922b75e-772b-458f-9bbe-e3c536da9874.png)
Seems very similar to issue #38 and might be solvable the same way.

The tarball from Github works fine, i.e. results in files with read permission (so I switched the Solus package to that for now).
If this is only a result of a quirk in the Solus build system I apologize, but I thought I should report this just in case there is an actual issue with the PyPI upload.

**Comment by mulkieran** [comment]
Yeah, my default umask is strictish, and I'm using a new tool. I'll see what I can do about automating the release process to make that problem go away, and then, probably put up a new patch release, etc., etc.

**Comment by mulkieran** [comment]
@Staudey Probably fixed now in new release. Thanks for letting me know.

**Comment by Staudey** [comment]
Thanks a lot! I've just checked and the PyPI files now have the correct permissions set.
