### ISSUE TITLE
Invoke GLib.io_add_watch() with wrong parameters

### ISSUE THREAD

**Issue by martin-belanger** [pyudev/pyudev#478]
In this file https://github.com/pyudev/pyudev/blob/master/src/pyudev/glib.py#L67, we find this:
```
            self.event_source = GLib.io_add_watch(
                self.monitor, GLib.IO_IN, self._process_udev_event
            )
```
However, the signature for `GLib.io_add_watch()` is this (ref: https://gitlab.gnome.org/GNOME/pygobject/-/blob/master/gi/overrides/GLib.py#L684):
```
GLib.io_add_watch(channel, priority, condition, func, *user_data)
```
The `priority` parameter is missing in `pyudev/glib.py`. I can submit a fix (i.e. add `glib.PRIORITY_DEFAULT`), but I wanted to make sure that this omission is indeed a bug and not something done on purpose.

**Comment by mulkieran** [comment]
Thanks for your interest! I'm afraid you're the authority on this, I only maintain this library, I've never used the functionality. So it would be easy for me to accept a well-justified patch.
