### ISSUE TITLE
Remove deprecated API.

### ISSUE THREAD

**Issue by lunaryorn** [pyudev/pyudev#48]
Remove all deprecated API.

# Affected members

- class `Device`:
  - `traverse()` (use `ancestors` instead)
- class `Monitor`:
  - `receive_device()` (use `poll()` instead)
  - `enable_receiving()` (use `start()` instead)
  - `__iter__()` (use explicit looping with `for event in iter(monitor.poll(), None)` or asynchronous monitoring with `MonitorObserver`)

**Comment by mulkieran** [comment]
All methods are deprecated in 0.17.
