### ISSUE TITLE
USB doesn't detect removal

### ISSUE THREAD

**Issue by Lvl4Sword** [pyudev/pyudev#482]
`udevadm --version` gives `249`, Ubuntu 22.04 LTS.
Python version `3.10.6`

pyudev doesn't seem to detect/emit anything for device.action being "remove".
Run the following code, and unplug a USB device. You'll see nothing is printed.
Plugging in a USB device works just fine, and the "add"/"change"/"bind" actions are emitted.

```py
import pyudev


context = pyudev.Context()
monitor = pyudev.Monitor.from_netlink(context)
monitor.filter_by('usb')
for device in iter(monitor.poll, None):
    if device.get('ID_VENDOR_ID') is not None and device.get('ID_MODEL_ID') is not None:
         print(device.action)
         print(device.items())
 ```

**Comment by mulkieran** [comment]
@Lvl4Sword Are 'ID_VENDOR_ID' and 'ID_MODEL_ID' necessarily included in a udev remove event? You may be filtering out the remove events w/ that if expression.

**Comment by Lvl4Sword** [comment]
@mulkieran I appreciate your response. That appears to be the case.
