### ISSUE TITLE
sys.getfilesystemencoding() in _util.py somtimes can be None

### ISSUE THREAD

**Issue by nylz** [pyudev/pyudev#68]
I had a problem with the following function:
pyudev._util.ensure_byte_string(value)

the application crashed with the following message:
   File "/home/username/coding/release/build/pyi.linux2/Phony/out00-PYZ.pyz/pyudev._util", line 53, in ensure_byte_string
   TypeError: encode() argument 1 must be string, not None

This is, because system.getfilesystemencoding() returns None if the system default encoding is used (see doc there).

so I created a little workaround and changed the part:

<    if not isinstance(value, bytes):
<       value = value.encode(sys.getfilesystemencoding())

--- to ---
>    if not isinstance(value, bytes):
>        if (sys.getfilesystemencoding() is not None):
>            value = value.encode(sys.getfilesystemencoding())
>        else: 
>            value = str(value)
>    return value

I did it similar in the ensure_unicode_string(value)-function, but used 'unicode(value)' there instead of 'str(value)'.

now it works for fine for me.

**Comment by mulkieran** [comment]
Please submit PR for this bug and reopen issue at that time.
