### ISSUE TITLE
Version on pypi is out of date and buggy

### ISSUE THREAD

**Issue by tdicola** [pyudev/pyudev#74]
I ran into a lot of problems trying to use pyudev installed from pypi with pip (from here: https://pypi.python.org/pypi/pyudev/0.16.1), specifically Monitor.poll was not working like the documentation showed it should work (it wasn't calling Monitor.start).  Digging in more it looks like this problem was fixed with this bug: https://github.com/pyudev/pyudev/issues/57  

Unfortunately the version of pyudev on pypi (version 0.16.1) doesn't include this fix and synchronous monitoring doesn't work as expected.  If I install the current code from github (looks like version 0.17) the issue is fixed and everything works just like the docs say it should work.  Since the docs say pyudev should be installed from pypi using pip, I think it would make sense to update the version on pypi so that bug fix is available.  

Alternatively perhaps mention in the docs that you need the latest code from github to use Monitor.poll?

Thanks for providing a great Python wrapper around udev!

**Comment by mulkieran** [comment]
Hopefully this is working now with new update. If it is not, please reopen.
