### ISSUE TITLE
test failures and some inconsistent links

### ISSUE THREAD

**Issue by frispete** [pyudev/pyudev#91]
Hello,

while preparing the current version of pyudev package for openSUSE, I discovered a few issues/inconsistencies:

 * some documentation links still point to lunaryorn:
   e.g.: https://secure.travis-ci.org/lunaryorn/pyudev.png?branch=develop
   and: git clone git://github.com/lunaryorn/pyudev.git

 * testing requires nose, that isn't listed in requirements
 * using a current version of nose results in many failing tests

You can see the current build state here:
https://build.opensuse.org/package/show/home:frispete:python/python-pyudev
(with tests disabled)

**Comment by mulkieran** [comment]
Hi!

I do fix broken links as I find them, but a PR from you would move things along a good deal faster.

The central repo is still github.com/pyudev/pyudev and lunaryorn/pyudev links to that.

I do not think testing does require nose, it seems to get along fine with pytest only.

- mulhern

**Comment by mulkieran** [comment]
Fixed by #100 .
